--------------------------------------------------------
--  파일이 생성됨 - 월요일-9월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD" 
   (	"NUM" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(60 BYTE), 
	"CONTENT" CLOB, 
	"FILENAME" VARCHAR2(60 BYTE), 
	"READCOUNT" NUMBER, 
	"IP" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE, 
	"RE_REF" NUMBER, 
	"RE_LEV" NUMBER, 
	"RE_SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SCOTT"."BOARD"."NUM" IS '게시글 번호';
   COMMENT ON COLUMN "SCOTT"."BOARD"."USERNAME" IS '로그인아이디 또는 작성자이름';
   COMMENT ON COLUMN "SCOTT"."BOARD"."PASSWD" IS '게시글 패스워드, 로그인안한사용자가 입력함';
   COMMENT ON COLUMN "SCOTT"."BOARD"."SUBJECT" IS '글제목';
   COMMENT ON COLUMN "SCOTT"."BOARD"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SCOTT"."BOARD"."FILENAME" IS '업로드한 파일명';
   COMMENT ON COLUMN "SCOTT"."BOARD"."READCOUNT" IS '조회수';
   COMMENT ON COLUMN "SCOTT"."BOARD"."IP" IS '글 작성자의 IP주소';
   COMMENT ON COLUMN "SCOTT"."BOARD"."REG_DATE" IS '글 작성날짜';
   COMMENT ON COLUMN "SCOTT"."BOARD"."RE_REF" IS '글 그룹';
   COMMENT ON COLUMN "SCOTT"."BOARD"."RE_LEV" IS '글 들여쓰기 레벨';
   COMMENT ON COLUMN "SCOTT"."BOARD"."RE_SEQ" IS '같은 글그룹 안에서의 글순서';
REM INSERTING into SCOTT.BOARD
SET DEFINE OFF;
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (4,'ccc',null,'글제목4',null,14,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),4,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (5,'ddd',null,'글제목5',null,4,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),5,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (6,'eee',null,'글제목6',null,4,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),6,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (7,'fff',null,'글제목7',null,3,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),7,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (8,'zzz',null,'글내용8',null,5,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),8,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (9,'일식이','1234','글제목9',null,4,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),9,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (11,'만식이','1234','글제목1',null,4,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),11,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (12,'천식이','1234','글제목1',null,10,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),12,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (13,'백식이','1234','글제목1',null,6,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),13,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (1,'홍길동','1234','글제목1',null,9,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),1,0,0);
Insert into SCOTT.BOARD (NUM,USERNAME,PASSWD,SUBJECT,FILENAME,READCOUNT,IP,REG_DATE,RE_REF,RE_LEV,RE_SEQ) values (10,'월식이','1234','글제목1글제목1글제목1',null,9,'0:0:0:0:0:0:0:1',to_date('19/08/28','RR/MM/DD'),10,0,0);
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BOARD_PK" ON "SCOTT"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("NUM" NOT NULL ENABLE);
